[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[dev]
  command = "npm run dev"
  port = 3000
  publish = "dist"
  targetPort = 3000

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Required for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
